- name: Create Folder Config file
  ansible.builtin.template:
    src: folder.xml
    dest: /tmp/folder.xml
    
- name: Create Folders
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{item}}"
    url: http://10.166.0.3:8080
    user: Phani
    password: "{{jenkins_password}}"
  loop:
    - CI Pipelines

- name: Apply tags to tasks
  ansible.builtin.include_tasks: pipeline.yml
  loop:
    - {name: "frontend" , dir: "CI Pipelines"}