- name: Create Folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://10.162.0.2:8080
    user: Phani
    password: "{{jenkins_password}}"
  loop: "{{ folders }}"