- name: Create Config file
  ansible.builtin.template:
    src: job1.xml
    dest: /temp/job1.xml
- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', 'tmp/job1.xml') }}"
    name: "{{item.name }}"
    url: http://10.162.0.2:8080
    user: Phani
    password: "{{jenkins_password}}"
  loop:
    - {name: "frontend"}
    - {name: "cart"}