- name: Create Folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://10.166.0.3:8080
    user: Phani
    password: "{{jenkins_password}}"
  loop: "{{folders}}"

- name: Create Single Pipeline Jobs
  ansible.builtin.include_tasks: sbranch-pipeline.yml
  loop: "{{ ci_pipeline_jobs }}"

- name: Create MultiBranch Pipeline Jobs
  ansible.builtin.include_tasks: mbranch-pipeline.yml
  loop: "{{ ci_pipeline_jobs }}"
