- name: Download jenkins cli
  ansible.builtin.get_url:
    url: http://10.166.0.3:8080/jnlpJars/jenkins-cli.jar
    dest: /opt/jenkins-cli.jar

- name: Check if Job exists or not - {{item.dir}}/{{item.name}}
  ansible.builtin.shell: java -jar /opt/jenkins-cli.jar -auth Phani:{{jenkins_password}} -s http://10.166.0.3:8080 -webSocket get-job {{item.dir}}/{{item.name}}
  register: out
  ignore_errors: yes

- name: Create Config file
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-job.xml
  when: out.rc == 3

- name: Create Job - "{{item.dir}}/{{item.name}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://10.166.0.3:8080
    user: Phani
    password: "{{jenkins_password}}"
  when: out.rc == 3
