folders:
  - CI Pipelines
#  - Infra


ci_pipeline_jobs:
  - {name: "frontend", dir: "CI Pipelines"}
  - {name: "cart", dir: "CI Pipelines"}
  - {name: "catalogue", dir: "CI Pipelines"}
  - {name: "user", dir: "CI Pipelines"}
  - {name: "payment", dir: "CI Pipelines"}
  - {name: "shipping", dir: "CI Pipelines"}


sbranch_pipeline_jobs:
#   - {name: "roboshop-ansible", dir: "CD"}
  - {name: "roboshop-infra", dir: "Infra"}
#  - {name: "roboshop-helm-chart", dir: "CD"}